sudo: required
language: c
services:
  - docker
 
install:
  - docker build -t hello .

script:
  - docker run hello

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi

