sudo: required
language: c
services:
  - docker
 
install:
  - docker build -t hello .

script:
  - docker run hello
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag hello duplexa/hello-test;
    docker push duplexa/hello-test;
    fi

after_success:
  - echo 'good'
