sudo: required
language: c
services:
  - docker

env:
  - LOCAL_NAME=hello REMOTE_NAME=duplexa/hello-test

install:
  - docker build -t $LOCAL_NAME .

script:
  - source test.sh

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ -a $TRAVIS_PULL_REQUEST ]; then
        docker tag $LOCAL_NAME $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
        docker push $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
      else 
        docker tag $LOCAL_NAME $REMOTE_NAME:latest;
        docker push $REMOTE_NAME:latest;
      fi
    fi
  - echo 'good'
  - date
  
