sudo: required
language: c
services:
  - docker
 
install:
  - docker build -t hello .

script:
  - source test.sh
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" -a $TRAVIS_PULL_REQUEST ]; then
      docker tag hello duplexa/hello-test:$TRAVIS_PULL_REQUEST_BRANCH;
      docker push duplexa/hello-test:$TRAVIS_PULL_REQUEST_BRANCH;
    fi

after_success:
  - echo 'good'
