sudo: required
language: c
services:
  - docker
 
install:
  - docker build -t hello .

script:
  - source test.sh

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
      docker tag hello duplexa/hello-test:$TRAVIS_BRANCH;
      docker push duplexa/hello-test:$TRAVIS_BRANCH;
    fi

